server {
    listen 82;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js)$ {
        try_files $uri =404;
        expires -1;
        access_log off;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
    }

    location ~* \.(png|jpg|jpeg|gif|ico|svg)$ {
        try_files $uri =404;
        expires 1y;
        access_log off;
        add_header Cache-Control "public, immutable";
    }

    location /api/webhook/ {
        # Maneja el preflight OPTIONS
        if ($request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
            add_header Access-Control-Allow-Headers "Content-Type";
            add_header Content-Length 0;
            return 204;
        }

        proxy_pass https://n8nvetcitas.nexuscampusinternational.com/webhook/;
        proxy_set_header Host n8nvetcitas.nexuscampusinternational.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "Content-Type";
    }
}
